"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from glean.datasources import Datasources
from glean.indexing_authentication import IndexingAuthentication
from glean.indexing_datasource import IndexingDatasource
from glean.indexing_documents import IndexingDocuments
from glean.indexing_permissions import IndexingPermissions
from glean.indexing_shortcuts import IndexingShortcuts
from glean.people import People


class Indexing(BaseSDK):
    documents: IndexingDocuments
    permissions: IndexingPermissions
    datasource: IndexingDatasource
    people: People
    datasources: Datasources
    authentication: IndexingAuthentication
    shortcuts: IndexingShortcuts

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.documents = IndexingDocuments(self.sdk_configuration)
        self.permissions = IndexingPermissions(self.sdk_configuration)
        self.datasource = IndexingDatasource(self.sdk_configuration)
        self.people = People(self.sdk_configuration)
        self.datasources = Datasources(self.sdk_configuration)
        self.authentication = IndexingAuthentication(self.sdk_configuration)
        self.shortcuts = IndexingShortcuts(self.sdk_configuration)
