fruit_data = {
    "Apple": {"color": "Red", "taste": "Sweet", "nutrients": ["fiber", "vitamin C"]},
    "Banana": {"color": "Yellow", "taste": "Sweet", "nutrients": ["potassium", "vitamin B6"]},
    "Banana": {"color": "Yellow", "taste": "Sweet", "nutrients": ["potassium", "vitamin B6"]},
    "Orange": {"color": "Orange", "taste": "Citrusy", "nutrients": ["vitamin C", "fiber"]},
    "Strawberry": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "manganese"]},
    "Grapes": {"color": "Green/Red/Purple", "taste": "Sweet/Tart", "nutrients": ["vitamin K", "vitamin C"]},
    "Mango": {"color": "Yellow/Orange", "taste": "Sweet", "nutrients": ["vitamin A", "vitamin C"]},
    "Blueberry": {"color": "Blue", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "vitamin K"]},
    "Pineapple": {"color": "Brown/Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "manganese"]},
    "Watermelon": {"color": "Green/Red", "taste": "Sweet", "nutrients": ["vitamin C", "vitamin A"]},
    "Peach": {"color": "Pink/Yellow", "taste": "Sweet", "nutrients": ["vitamin A", "vitamin C"]},
    "Cherry": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "potassium"]},
    "Pear": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["fiber", "vitamin C"]},
    "Kiwi": {"color": "Brown/Green", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "vitamin K"]},
    "Papaya": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin C", "folate"]},
    "Plum": {"color": "Purple/Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "vitamin K"]},
    "Raspberry": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["fiber", "vitamin C"]},
    "Blackberry": {"color": "Black", "taste": "Sweet/Tart", "nutrients": ["fiber", "vitamin C"]},
    "Lemon": {"color": "Yellow", "taste": "Sour", "nutrients": ["vitamin C", "fiber"]},
    "Lime": {"color": "Green", "taste": "Sour", "nutrients": ["vitamin C", "fiber"]},
    "Apricot": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin A", "vitamin C"]},
    "Avocado": {"color": "Green", "taste": "Creamy", "nutrients": ["healthy fats", "fiber"]},
    "Cantaloupe": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin A", "vitamin C"]},
    "Dragon Fruit": {"color": "Pink/White", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Fig": {"color": "Purple/Green", "taste": "Sweet", "nutrients": ["fiber", "calcium"]},
    "Guava": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Jackfruit": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Lychee": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "copper"]},
    "Mandarin": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Mulberry": {"color": "Red/Black", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "iron"]},
    "Nectarine": {"color": "Orange/Red", "taste": "Sweet", "nutrients": ["vitamin A", "vitamin C"]},
    "Olive": {"color": "Green/Black", "taste": "Salty", "nutrients": ["healthy fats", "vitamin E"]},
    "Passion Fruit": {"color": "Purple/Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Pomegranate": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Quince": {"color": "Yellow", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Starfruit": {"color": "Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Tangerine": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Ugli Fruit": {"color": "Green/Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Cranberry": {"color": "Red", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Gooseberry": {"color": "Green/Red", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Honeydew": {"color": "Green", "taste": "Sweet", "nutrients": ["vitamin C", "potassium"]},
    "Kumquat": {"color": "Orange", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Loquat": {"color": "Yellow/Orange", "taste": "Sweet/Tart", "nutrients": ["vitamin A", "fiber"]},
    "Persimmon": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin A", "fiber"]},
    "Rambutan": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "copper"]},
    "Soursop": {"color": "Green", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Tamarind": {"color": "Brown", "taste": "Sweet/Tart", "nutrients": ["fiber", "magnesium"]},
    "White Currant": {"color": "White", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Yellow Passion Fruit": {"color": "Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Zucchini": {"color": "Green", "taste": "Mild", "nutrients": ["vitamin C", "fiber"]},
    "Acerola": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "vitamin A"]},
    "Bilberry": {"color": "Blue", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Boysenberry": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Clementine": {"color": "Orange", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Elderberry": {"color": "Black", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Feijoa": {"color": "Green", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Gac": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "beta-carotene"]},
    "Huckleberry": {"color": "Blue", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Indian Fig": {"color": "Green", "taste": "Sweet", "nutrients": ["fiber", "calcium"]},
    "Jujube": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Kiwano": {"color": "Orange", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Longan": {"color": "Brown", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Mangosteen": {"color": "Purple", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Medlar": {"color": "Brown", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Miracle Fruit": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Nance": {"color": "Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Noni": {"color": "Green/White", "taste": "Bitter", "nutrients": ["vitamin C", "fiber"]},
    "Pitaya": {"color": "Pink/White", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Prickly Pear": {"color": "Green/Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Salak": {"color": "Brown", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Sapodilla": {"color": "Brown", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Sea Buckthorn": {"color": "Orange", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Surinam Cherry": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Sweet Lime": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Velvet Apple": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Wolfberry": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Yuzu": {"color": "Yellow", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Ackee": {"color": "Red/Yellow", "taste": "Savory", "nutrients": ["vitamin C", "fiber"]},
    "Breadfruit": {"color": "Green", "taste": "Starchy", "nutrients": ["vitamin C", "fiber"]},
    "Chayote": {"color": "Green", "taste": "Mild", "nutrients": ["vitamin C", "fiber"]},
    "Cherimoya": {"color": "Green", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Custard Apple": {"color": "Green", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Durian": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Elephant Apple": {"color": "Green", "taste": "Tart", "nutrients": ["vitamin C", "fiber"]},
    "Gac Fruit": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Horned Melon": {"color": "Orange", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Jabuticaba": {"color": "Purple", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Langsat": {"color": "Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Mammee Apple": {"color": "Brown", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Marang": {"color": "Green", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Mountain Apple": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Pawpaw": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Pequi": {"color": "Yellow", "taste": "Savory", "nutrients": ["vitamin C", "fiber"]},
    "Pulasan": {"color": "Red", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Santol": {"color": "Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "Soncoya": {"color": "Brown", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Sugar Apple": {"color": "Green", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Tamarillo": {"color": "Red/Yellow", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]},
    "White Sapote": {"color": "Green/Yellow", "taste": "Sweet", "nutrients": ["vitamin C", "fiber"]},
    "Yangmei": {"color": "Red", "taste": "Sweet/Tart", "nutrients": ["vitamin C", "fiber"]}
    
    
    # Add more fruits...
}

def get_fruit_info(name):
    return fruit_data.get(name.title(), "Fruit not found.")
