# Generated by Django 5.0.9 on 2024-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netauto_plugin', '0003_alter_flexapplication_health_monitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexapplication',
            name='dst_address_string',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='status',
            field=models.CharField(default='new', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='l4application',
            name='dst_address_string',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='l4application',
            name='status',
            field=models.CharField(default='new', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='dst_address_string',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='status',
            field=models.CharField(default='new', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='flexapplication',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='flexapplication',
            name='persistence_profile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='l4application',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='l4application',
            name='persistence_profile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mtlsapplication',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mtlsapplication',
            name='persistence_profile',
            field=models.CharField(max_length=50),
        ),
    ]
