# Generated by Django 5.0.9 on 2024-09-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netauto_plugin', '0007_alter_flexapplication_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexapplication',
            name='health_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_netauto_plugin.healthmonitor'),
        ),
        migrations.AlterField(
            model_name='l4application',
            name='health_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_netauto_plugin.healthmonitor'),
        ),
        migrations.AlterField(
            model_name='mtlsapplication',
            name='health_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='netbox_netauto_plugin.healthmonitor'),
        ),
    ]
