"""
This type stub file was generated by pyright.
"""

from .loss import AbsoluteError, HalfBinomialLoss, HalfGammaLoss, HalfMultinomialLoss, HalfPoissonLoss, HalfSquaredError, HalfTweedieLoss, HalfTweedieLossIdentity, HuberLoss, PinballLoss

"""
The :mod:`sklearn._loss` module includes loss function classes suitable for
fitting classification and regression tasks.
"""
__all__ = ["HalfSquaredError", "AbsoluteError", "PinballLoss", "HuberLoss", "HalfPoissonLoss", "HalfGammaLoss", "HalfTweedieLoss", "HalfTweedieLossIdentity", "HalfBinomialLoss", "HalfMultinomialLoss"]
