from _typeshed import Incomplete

PING_THRESHOLD: float
RATE_LIMIT_THRESHOLD: int
logger: Incomplete

class RPCQualityError(Exception):
    message: Incomplete
    def __init__(self, message: str) -> None: ...

class RPCNotReachableError(RPCQualityError): ...
class RPCNotRPCError(RPCQualityError): ...
class RPCRateLimitError(RPCQualityError): ...
class RPCUnstableError(RPCQualityError): ...

class RPCChecker:
    rpc_url: Incomplete
    def __init__(self, rpc_url: str) -> None: ...
    def check(self) -> None: ...
