from datetime import datetime
from dojo.common.constants import Chain as Chain
from dojo.utils import disk_cache as disk_cache
from web3.types import Timestamp

def block_to_timestamp(rpc_url: str, block_number: int) -> Timestamp: ...
def block_to_datetime(rpc_url: str, block_number: int) -> datetime: ...
def closest_block_to(datetime_: datetime, chain: Chain) -> int: ...
def closest_block_lt(target_timestamp: Timestamp, chain: Chain) -> int: ...
