from . import interfaces as interfaces
from _typeshed import Incomplete

class ConnectionPool(interfaces.ConnectionPoolInterface):
    pool: Incomplete
    def __init__(self, password: str, user: str = 'root', host: str = 'localhost', port: int = 3306, database: str | None = None) -> None: ...
    def runsql(self, sql: str, placeholders: tuple | None = None) -> int: ...
    def select(self, sql: str) -> interfaces.ReturnedSqlType: ...
