# Generated by Django 1.10.2 on 2016-12-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('teamspeak3', '0002_auto_20161212_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamspeak3User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teamspeak3', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=254)),
                ('perm_key', models.CharField(max_length=254)),
            ],
        ),
    ]
