from .filesystem import FILE_SYSTEM_BLUEPRINT
from .postgres import POSTGRES_BLUEPRINT
from .redis import REDIS_BLUEPRINT

SYSTEM_PLUGINS = [FILE_SYSTEM_BLUEPRINT, POSTGRES_BLUEPRINT, REDIS_BLUEPRINT]
