# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Account Receivable Penalty",
    "version": "14.0.3.7.0",
    "category": "Accounting",
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_account_move_line_day_overdue",
        "ssi_master_data_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_company_currency_mixin",
        "base_automation",
        "ssi_state_change_history_mixin",
        "ssi_localdict_mixin",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "ir_module_category/batch_receivable_penalty_computation.xml",
        "res_groups/batch_receivable_penalty_computation.xml",
        "ir_model_access/batch_receivable_penalty_computation.xml",
        "ir_model_access/batch_receivable_penalty_computation_detail.xml",
        "ir_rule/batch_receivable_penalty_computation.xml",
        "ir_sequence/batch_receivable_penalty_computation.xml",
        "sequence_template/batch_receivable_penalty_computation.xml",
        "policy_template/batch_receivable_penalty_computation.xml",
        "approval_template/batch_receivable_penalty_computation.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/receivable_penalty_policy_data.xml",
        "data/receivable_penalty_comp_policy_data.xml",
        "data/approval_template_data.xml",
        "data/ir_actions_server_data.xml",
        "data/base_automation_data.xml",
        "data/account_journal_data.xml",
        "wizards/create_penalty_from_computation_views.xml",
        "wizards/create_penalty_computation_from_move_views.xml",
        "views/account_receivable_penalty_type_views.xml",
        "views/account_receivable_penalty_computation_views.xml",
        "views/account_receivable_penalty_views.xml",
        "views/batch_receivable_penalty_computation_views.xml",
        "views/account_move_line_views.xml",
    ],
    "demo": [
        "demo/account_journal_demo.xml",
        "demo/account_account_demo.xml",
        "demo/account_receivable_penalty_type_demo.xml",
    ],
    "images": [],
}
