"""
Type stubs for Vortex client exceptions.
"""

class VortexClientError(Exception): ...
class ValidationError(VortexClientError): ...
class ConnectionError(VortexClientError): ...
class ProducerError(VortexClientError): ...
class ConsumerError(VortexClientError): ...
class AnalysisError(VortexClientError): ...
