from setuptools import setup, find_packages

setup(
    name="ibkrtools",
    version="0.1.0",
    author="Stavros Klaoudatos",
    author_email="stavrosklaoudatos@gmail.com",
    description="A modern Python wrapper for Interactive Brokers TWS API",
    long_description=open("README.md", "r", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/StavrosKlaoudatos/IBKRTools",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.8",
    install_requires=[
        "ibapi>=9.81.1",
        "pandas>=1.3.0",
        "pytz>=2021.1",
        "python-dateutil>=2.8.2",
        "holidays>=0.13",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Office/Business :: Financial",
        "Topic :: Office/Business :: Financial :: Investment",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="interactive brokers, trading, finance, algorithmic trading, market data",
)
