# Generated by Django 5.0.9 on 2024-09-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netauto_plugin', '0002_alter_flexapplication_dst_address_l4application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexapplication',
            name='health_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_health_monitors', to='netbox_netauto_plugin.healthmonitor'),
        ),
        migrations.AlterField(
            model_name='l4application',
            name='health_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_health_monitors', to='netbox_netauto_plugin.healthmonitor'),
        ),
        migrations.AlterField(
            model_name='mtlsapplication',
            name='health_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_health_monitors', to='netbox_netauto_plugin.healthmonitor'),
        ),
    ]
