# Generated by Django 5.0.9 on 2025-01-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_netauto_plugin', '0024_flexapplication_access_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='l4application',
            name='vlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.vlan'),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='vlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.vlan'),
        ),
    ]
