from sator_core.ports.driving.extraction.attributes.patch import PatchAttributesExtractionPort
from sator_core.ports.driving.extraction.attributes.product import ProductAttributesExtractionPort
from sator_core.ports.driving.extraction.attributes.vulnerability import VulnerabilityAttributesExtractionPort
