__all__ = [
    "ABC",
    "abstractmethod",
    "Union",
    "Literal",
    "Optional",
    "Callable",
    "Dict",
    "List",
    "Tuple",
    "Mapping",
    "Set",
    "TypedDict",
    "TypeAlias",
    "AnyStr",
    "Array",
    "Path",
    "Deque",
    "Any",
    "TypeGuard",
    "TYPE_CHECKING",
    "Annotated",
    "ClassVar",
    "Sequence",
    "namedtuple",
    "OrderedDict",
    "overload",
    "TypeVar",
    "DefaultDict",
    "AbstractSet",
    "Generator",
    "NamedTuple",
    "PathType",
    "Iterable",
    "Iterator",
    "Sized",
    "Text",
    "Self",
    "NotRequired",
    "NoReturn",
    "PathLike",
    "Unpack",
    "Number",
    "Type",
    "T",
    # related functions
    "get_args",
    "get_origin",
    "get_overloads",
    "get_type_hints",
]

from abc import ABC, abstractmethod

from typing import (
    Any,
    Union,
    Optional,
    Literal,
    Callable,
    Generator,
    NamedTuple,
    Iterable,
    Iterator,
    Sized,
    Dict,
    List,
    Tuple,
    Type,
    Mapping,
    Set,
    Deque,
    DefaultDict,
    TypedDict,
    TypeAlias,
    TypeGuard,
    NotRequired,
    TYPE_CHECKING,
    Sequence,
    TypeVar,
    Annotated,
    AbstractSet,
    NoReturn,
    ClassVar,
    Unpack,
    Self,
    overload,
    get_args,
    get_origin,
    get_overloads,
    get_type_hints,
)
from numbers import Number
from collections import namedtuple, OrderedDict
from pathlib import Path
from os import PathLike

T = TypeVar("T")  # Any type.
PathType: TypeAlias = Union[PathLike, str, bytes]
Text: TypeAlias = Union[str, bytes]
AnyStr: TypeAlias = Union[bytes, str]
Array: TypeAlias = Union[list, tuple]
