from setuptools import setup, find_packages

setup(
    name='pydatamax',
    version='0.1.11',
    packages=find_packages(),
    install_requires=[
        'ebooklib',
        'python-docx',
        'beautifulsoup4',
        "python-dotenv",
        "minio",
        "loguru",
        "tqdm",
        "oss2",
        "python-docx",
        "openai",
        "jionlp",
        "chardet",
        "python-pptx",
        "openpyxl",
        "pymupdf",
        "langchain_community==0.2.9",
        "premailer",
        "setuptools==75.3.0",
        "docx2markdown",
        "tiktoken",
        "markitdown",
        "pandas",
        "xlrd",
        "tabulate",
        "unstructured[all]",
        "markdown"
    ],
    author='hzb | ccy',
    author_email='zhibaohe@hotmail.com | cy.kron@foxmail.com',
    description='A library for parsing and converting various file formats.',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/cosco/datamax',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.10',
)