# Generated by Django 5.0.9 on 2024-11-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netauto_plugin', '0015_alter_flexapplication_health_monitor_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l4application',
            name='health_monitor_profile',
        ),
        migrations.RemoveField(
            model_name='l4application',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='l4application',
            name='receive_string',
        ),
        migrations.RemoveField(
            model_name='l4application',
            name='send_string',
        ),
        migrations.RemoveField(
            model_name='l4application',
            name='timeout',
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='client_ssl_auth_mode',
            field=models.CharField(default='tbd', max_length=50),
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='client_ssl_cert_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='client_ssl_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='client_ssl_auth_mode',
            field=models.CharField(default='tbd', max_length=50),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='client_ssl_cert_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='client_ssl_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
