# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
# pylint: disable=C8101
{
    "name": "HR - Recruitment",
    "version": "14.0.1.0.0",
    "website": "https://simetri-sinergi.id",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "mail",
        "ssi_hr_employee",
        "ssi_hr_employee_personal_from_work_address",
        "ssi_hr_employee_experience_from_work_address",
        "ssi_hr_employee_language_from_work_address",
        "ssi_hr_employee_identification_from_work_address",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_duration_mixin",
        "ssi_state_change_history_mixin",
        "base_automation",
    ],
    "data": [
        "menu.xml",
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/multiple_approval/recruitment_applicant_approval_template_data.xml",
        "data/multiple_approval/recruitment_vacancy_approval_template_data.xml",
        "data/sequence/ir_sequence_data.xml",
        "data/sequence/recruitment_applicant_sequence_template_data.xml",
        "data/sequence/recruitment_vacancy_sequence_template_data.xml",
        "data/policy/recruitment_applicant_policy_template_data.xml",
        "data/policy/recruitment_vacancy_policy_template_data.xml",
        "data/automation/ir_actions_server_data.xml",
        "data/automation/base_automation_data.xml",
        "views/recruitment_stage_views.xml",
        "views/recruitment_stage_result_views.xml",
        "views/recruitment_applicant_views.xml",
        "views/recruitment_vacancy_views.xml",
    ],
}
