def round_to_nearest_n(x: float, n: int) -> int: ...
def div_round_up(numerator: int, denominator: int) -> int: ...
def integerdiv(a: int, b: int, roundup: bool) -> int: ...
def test_round_to_nearest_n() -> None: ...
