# Generated by Django 5.0.9 on 2024-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_netauto_plugin', '0010_rename_dst_address_flexapplication_virtual_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l4application',
            name='health_monitor',
        ),
        migrations.RemoveField(
            model_name='flexapplication',
            name='health_monitor',
        ),
        migrations.RemoveField(
            model_name='mtlsapplication',
            name='health_monitor',
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='receive_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='send_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='flexapplication',
            name='timeout',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='l4application',
            name='interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='l4application',
            name='receive_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='l4application',
            name='send_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='l4application',
            name='timeout',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='receive_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='send_string',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mtlsapplication',
            name='timeout',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.DeleteModel(
            name='HealthMonitor',
        ),
    ]
