"""
This type stub file was generated by pyright.
"""

import os
from ._check_build import check_build

"""Module to give helpful messages to the user that did not
compile scikit-learn properly.
"""
INPLACE_MSG = ...
STANDARD_MSG = ...
def raise_build_error(e):
    ...

