from typing import Any, Callable

def cached(function_version: str = '') -> Callable[[Callable[_Param, _Return]], Callable[_Param, _Return]]: ...
def use_presaved_data(args_kwargs_to_save: list[tuple[Any, dict[Any, Any]]], function_version: str = '') -> Callable[[Callable[_Param, _Return]], Callable[_Param, _Return]]: ...
def test_cached() -> None: ...
def test_presaved_data() -> None: ...
