"""
Type stubs for ddtrace utility functions.
"""

from contextlib import contextmanager
from typing import Any, Generator, Optional

def has_ddtrace_dependency() -> bool: ...
@contextmanager
def trace(name: str, **kwargs: Any) -> Generator[Optional[Any], None, None]: ...
def _suppress_ddtrace_logs() -> None: ...
def _preload_psutil_muted_traceback() -> None: ...
