import datetime
import logging
from _typeshed import Incomplete

class DojoLogFilter(logging.Filter):
    def __init__(self) -> None: ...

class NotLogFilter(logging.Filter):
    inner: Incomplete
    def __init__(self, inner: logging.Filter) -> None: ...
    def filter(self, record: logging.LogRecord) -> bool: ...
LogLevel = int

def set_normal_logging_config(*, dojo_log_level: LogLevel = ..., global_log_level: LogLevel = ...) -> None: ...
def set_normal_logging_config_and_print_explanation(*, dojo_log_level: LogLevel = ..., global_log_level: LogLevel = ..., pause_for_reading_length: datetime.timedelta = ...) -> None: ...
