from enum import Enum

class JobOrderStatus(str, Enum):
    PAYMENT_VALIDATED = 'PAYMENT_VALIDATED'
    ORDER_CANCELLED = 'ORDER_CANCELLED'
    SHIPPING_LABEL_SENT_TO_SELLER = 'SHIPPING_LABEL_SENT_TO_SELLER'
    ORDER_SHIPPED = 'ORDER_SHIPPED'
    DELIVERED_TO_POST_OFFICE_OR_PICKUP_POINT = 'DELIVERED_TO_POST_OFFICE_OR_PICKUP_POINT'
    ORDER_RECEIVED = 'ORDER_RECEIVED'
    ORDER_FINALIZED = 'ORDER_FINALIZED'
    RETURN_INITIATED = 'RETURN_INITIATED'
    REFUND_DONE = 'REFUND_DONE'
    ORDER_CANCELED_ITEM_UNAVAILABLE = 'ORDER_CANCELED_ITEM_UNAVAILABLE'
    ORDER_CANCELLED_BY_VINTED = 'ORDER_CANCELLED_BY_VINTED'
    ORDER_DISPUTE_STARTED = 'ORDER_DISPUTE_STARTED'
    ORDER_CANCELLED_DUE_TO_LATE_SHIPPING = 'ORDER_CANCELLED_DUE_TO_LATE_SHIPPING'
    SHIPPING_LABEL_ORDERED = 'SHIPPING_LABEL_ORDERED'
    UNKNOWN = 'UNKNOWN'
