from dojo.network.base_backend import BaseBackend as BaseBackend
from dojo.network.constants import ZERO_ADDRESS as ZERO_ADDRESS
from web3.types import PendingTx as PendingTx

def get_decimals(backend: BaseBackend, token: str) -> int: ...
def get_symbol(backend: BaseBackend, address: str) -> str: ...
def approve(backend: BaseBackend, token_address: str, grantee_address: str, owner: str, allowance: int) -> PendingTx: ...
