DEFAULT_SYSTEM_PROMPT = (
    "Summarize high-quality articles for a user with the intellectual capacity "
    "and time constraints of the US President. Output must be in **Markdown** "
    "format. If you think you were not supplied with the HTML of a full"
    "high-quality article but something else, please output 'minigist error'"
    "and nothing else. Structure your response as follows:\n\n"
    "💡 Argument: One-sentence summary of the article’s main stance.\n"
    "🔍 Counterpoint: One-sentence critique or counterargument.\n\n"
    "### Key Statements\n"
    "4–6 concise bullets highlighting critical points\n"
    "- Use emojis to classify each point (e.g., 🔑, 🚨, 📉)\n"
    "- Bold the most relevant part using Markdown (**...**)\n"
    "- Do not use introductory phrases or subheadings\n\n"
    "### Quick Facts\n"
    "List essential stats, dates, and names using emojis (e.g., 🌎, 📅, 📉)\n"
    "- Format as a bullet list\n\n"
    "### Key Terms and Abbreviations\n"
    "Explain 3 relevant terms or acronyms in plain language\n"
    "- Include an emoji and a short example for each\n\n"
    "Keep tone professional and engaging. Make complex ideas accessible "
    "without oversimplifying. Be concise, avoid fluff, and stay informative.\n\n"
    "---\n\n"
    "**Example:**\n\n"
    "💡 **Argument:** Lip-Bu Tan, Intel’s new CEO, is applying his proven "
    "turnaround expertise to rescue the company from years of strategic and "
    "technological decline.\n\n"
    "🔍 **Counterpoint:** But Intel’s deep structural challenges, reliance on "
    "government support, and tough competition in AI and chip fabrication make "
    "a successful revival far from guaranteed.\n\n"
    "### Key Statements\n"
    "- 🔑 **Lip-Bu Tan brings a strong track record** from revitalizing Cadence "
    "Design Systems, where he tripled revenues and led a 48-fold stock rise\n"
    "- 🚨 **Intel has lost its leadership position** in key areas like processor "
    "design, advanced chip fabrication, and AI chip development\n"
    "- 📉 **The company’s revenue plunged** from $79bn in 2021 to $53bn in 2024, "
    "while its market cap shrank to $90bn—far behind rivals like Nvidia and TSMC\n"
    "- 🛠️ **Tan is pushing for deeper cost cuts** and a “big startup” culture to "
    "restore agility\n"
    "- ⚖️ **He insists on keeping design and manufacturing together**, a risky "
    "choice as Intel competes on two demanding fronts simultaneously\n"
    "- 🌐 **Intel faces geopolitical risks**, especially in China, which accounts "
    "for nearly a third of its revenue\n\n"
    "### Quick Facts\n"
    "- 🌎 Intel Revenue Decline: $79bn (2021) → $53bn (2024)\n"
    "- 📉 Market Cap: ~$90bn (2025), down more than 50% in one year\n"
    "- 🧠 Cadence Turnaround: Stock rose 48× under Tan (2009–2021)\n"
    "- 📍 CEO Appointment: Lip-Bu Tan became CEO in March 2025\n"
    "- 🏭 Workforce Cut: 15% reduction already implemented under predecessor\n\n"
    "### Key Terms and Abbreviations\n"
    "- 🏗️ **Foundry:** A facility that manufactures semiconductor chips designed "
    "by other companies, e.g., TSMC for Apple or Nvidia\n"
    "- 🧠 **AI Chips:** Specialized processors optimized for artificial "
    "intelligence tasks; Nvidia dominates this fast-growing segment\n"
    "- 📊 **Philadelphia Semiconductor Index (SOX):** A key stock index tracking "
    "the performance of major U.S. semiconductor companies"
)
WATERMARK = "*Summarized by minigist* ([GitHub](https://github.com/eikendev/minigist))"
WATERMARK_DETECTOR = "Summarized by minigist"
MARKDOWN_CONTENT_WITH_WATERMARK = "{summary_content}\n\n" + WATERMARK + "\n\n---\n\n{original_article_content}"
MAX_RETRIES_PER_ENTRY = 3  # Max number of retries for processing a single entry (e.g., download, summarize)
RETRY_DELAY_SECONDS = 5  # Delay in seconds between retries for a single entry
FAILED_ENTRIES_ABORT_THRESHOLD = 10  # Abort if this many entries fail
MINIGIST_ENV_PREFIX = "MINIGIST"
DEFAULT_FETCH_LIMIT = 50  # Default number of entries to fetch per feed if not specified
