from __future__ import annotations

from ..data import DNASeq

class FASTADNARecord:
    @property
    def sequence(self) -> DNASeq: ...
    @property
    def description(self) -> str: ...

class FASTADNAReader:
    def __init__(self, path: str): ...
    def __iter__(self) -> FASTADNAReader: ...
    def __next__(self) -> FASTADNARecord: ...
